### ISSUE TITLE
Travis CI dependencies caching

### ISSUE THREAD

**Issue by gmariotti** [vert-x3/issues#447]
This issue is for tracking all projects that need to have their `.travis.yml` updated based on [this discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vertx-dev/dYAxWHuYB6o/sj9trzyaBwAJ)

In practice it means adding the following lines

```
branches:
  only:
  - master
  - /^\d+\.\d+$/
----- FROM HERE -----
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/vertx/
----- TO HERE -----
jobs:
```

Projects:
- [x] vertx-amqp-client
- [x] vertx-kotlin-lang
- [x] vertx-web
- [x] vertx-junit5
- [x] vertx-rabbitmq-client
- [x] vertx-sql-common
- [x] vertx-unit
- [x] vertx-jdbc-client
- [x] vertx-mongo-client
- [x] vertx-service-proxy
- [x] vertx-health-check
- [x] vertx-kafka-client
- [x] vertx-proton
- [x] vertx-reactive-streams
- [x] vertx-redis-client
- [x] vertx-auth
- [x] vertx-grpc
- [x] vertx-consul-client
- [x] vertx-dropwizard-metrics
- [x] vertx-circuit-breaker
- [x] vertx-mqtt
- [x] vertx-micrometer-metrics
- [x] vertx-bridge-common
- [x] vertx-mail-client
- [x] vertx-service-factory
- [x] vertx-stomp
- [x] vertx-tcp-eventbus-bridge
- [x] vertx-camel-bridge
- [x] vertx-rx
- [x] vertx-http-service-factory
- [x] vertx-lang-js
- [x] vertx-lang-groovy
- [x] vertx-lang-ruby
- [x] vertx-config
- [x] vertx-service-discovery
- [x] vertx-maven-service-factory
- [x] vertx-sync
- [x] vertx-sockjs-service-proxy
- [x] vertx-cassandra-client
- [x] vertx-lang-scala
- [x] vertx-hazelcast
- [x] vertx-infinispan
- [x] vertx-amqp-bridge
- [x] vertx-embedded-mongo-db
- [x] vertx-client-services
- [x] vertx-mysql-postgresql-client
- [x] vertx-jca
